FROM homeassistant/home-assistant:dev

WORKDIR /usr/src

## Setup Home Assistant
COPY . homeassistant/
RUN \
    pip3 install -r homeassistant/requirements_all.txt && \
    pip3 uninstall -y typing uuid \
    && pip3 install \
    -e ./homeassistant \
    && python3 -m compileall homeassistant/homeassistant
